load("@rules_java//java:defs.bzl", "java_library")

java_binary(
    name = "HelloWorld",
    srcs = ["HelloWorld.java"],
    main_class = "example.program.HelloWorld",
    deps = ["//src/main/java/example/program/functions:Functions"],
)
